
export const STATUS={
  PENDING:'Pending',
  ARCHIVED:'Archived',
  SKIPPED:"Skipped",
  COMPLETED:'Completed',
  SCHEDULED:'Scheduled',
}

export const FILTER_OPTIONS = [
{ value: STATUS.PENDING, label: STATUS.PENDING },
{ value: STATUS.COMPLETED, label: STATUS.COMPLETED },
{ value: STATUS.SCHEDULED, label: STATUS.SCHEDULED },
{ value: STATUS.ARCHIVED, label: STATUS.ARCHIVED },
{ value: STATUS.SKIPPED, label: STATUS.SKIPPED },
]




export const dummyData = [
  {
    id: 1,
    title: "Complete Project Proposal",
    description: "Draft and finalize the project proposal document",
    status:STATUS.PENDING,
    scheduledDate: new Date("2023-06-15"),
    createdDate: new Date("2023-06-10"),
    completionDate: null,
    skippedDate: null,
    archivedDate: null,
    tag: "Personal",
    priority: 3,
    important: true,
    urgent: false,
    estimatedTimeInMins: 4,
  },
  {
    id: 2,
    title: "Call Mom",
    description: "Check up on mom and discuss weekend plans",
    status: STATUS.COMPLETED,
    scheduledDate: new Date("2023-06-13"),
    createdDate: new Date("2023-06-12"),
    completionDate: null,
    skippedDate: null,
    archivedDate: null,
    tag:"family",
    priority: 2,
    important: true,
    urgent: false,
    estimatedTimeInMins: 1,
  },
  {
    id: 3,
    title: "Research New Marketing Strategies",
    description:
      "Explore innovative marketing techniques for the upcoming campaign",
    status: STATUS.SCHEDULED,
    scheduledDate: null,
    createdDate: new Date("2023-06-08"),
    completionDate: new Date("2023-06-11"),
    skippedDate: null,
    archivedDate: null,
    tag: "work",
    priority: 4,
    important:true, 
    urgent: false,
    estimatedTimeInMins: 6,
  },
  // {
  //   id: 4,
  //   title: "Complete Project Proposal",
  //   description: "Draft and finalize the project proposal document",
  //   completed: false,
  //   skipped: false,
  //   archived: false,
  //   scheduled: true,
  //   scheduledDate: new Date("2023-06-15"),
  //   createdDate: new Date("2023-06-10"),
  //   completionDate: null,
  //   skippedDate: null,
  //   archivedDate: null,
  //   tags: ["Personal"],
  //   priority: 3,
  //   importance: 4,
  //   urgency: 2,
  //   timeEstimate: 4,
  // },
  // {
  //   id: 5,
  //   title: "Complete Project Proposal",
  //   description: "Draft and finalize the project proposal document",
  //   completed: false,
  //   skipped: false,
  //   archived: false,
  //   scheduled: true,
  //   scheduledDate: new Date("2023-06-15"),
  //   createdDate: new Date("2023-06-10"),
  //   completionDate: null,
  //   skippedDate: null,
  //   archivedDate: null,
  //   tags: ["Personal"],
  //   priority: 3,
  //   importance: 4,
  //   urgency: 2,
  //   timeEstimate: 4,
  // },
  // {
  //   id: 6,
  //   title: "Complete Project Proposal",
  //   description: "Draft and finalize the project proposal document",
  //   completed: false,
  //   skipped: false,
  //   archived: false,
  //   scheduled: true,
  //   scheduledDate: new Date("2023-06-15"),
  //   createdDate: new Date("2023-06-10"),
  //   completionDate: null,
  //   skippedDate: null,
  //   archivedDate: null,
  //   tags: ["Personal"],
  //   priority: 3,
  //   importance: 4,
  //   urgency: 2,
  //   timeEstimate: 4,
  // },
  // {
  //   id: 7,
  //   title: "Complete Project Proposal",
  //   description: "Draft and finalize the project proposal document",
  //   completed: false,
  //   skipped: false,
  //   archived: false,
  //   scheduled: true,
  //   scheduledDate: new Date("2023-06-15"),
  //   createdDate: new Date("2023-06-10"),
  //   completionDate: null,
  //   skippedDate: null,
  //   archivedDate: null,
  //   tags: ["Personal"],
  //   priority: 3,
  //   importance: 4,
  //   urgency: 2,
  //   timeEstimate: 4,
  // },
];
